spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: http://localhost:3001
              predicates:
                - Path=/api/v1/customers/**
            - id: product-service
              uri: http://localhost:3002
              predicates:
                - Path=/api/v2/products/**
            - id: order-service
              uri: http://localhost:3003
              predicates:
                - Path=/api/v3/orders/**